name: 🐛 Bug Report
description: Report a bug
labels: [Bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Behavior
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
    validations:
      required: false

  - type: input
    id: commitHash
    attributes:
      label: Commit Hash
      description: |
        Please make sure to run `git pull` before reporting any issues as it may have already been fixed.
    validations:
      required: true
